/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'teekay' at '8/10/16 12:40 PM' with Gradle 2.14
 *
 * @author teekay, @date 8/10/16 12:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
